### ISSUE TITLE
Issues with README

### ISSUE THREAD

**Issue by Jiajie-Mai** [ronishi1/Maze-Runner#2]
In accordance with the homework, I am required to comment on this. I apologize if this is late, but this is the earliest that I can do the commenting part of the homework. Looking over your README and today's class information, I will attempt to pick out the issues with the README.

Your problem seems legit as it is repeated with other groups that I have inspected: 
Return a boolean value to the problem along the lines of: 'does a single path exist from the explorer to the treasure?'

The recursive abstraction seems to hit a snag though. It is used to make a smaller version of itself, however, with your attempts to combine the problem within the recursive abstraction, it fails to make a smaller version of itself as you return different boolean values representing the existence of a path.

Your base cases seem spot-on with the base cases we discussed in class. The smallest version of a maze is if the explorer is on the treasure, this signals that a solution is found while the explorer stuck outside the maze has no valid moves and returns false for your problem.

Your pseudocode seems pretty straightforward except for the last line that says: 

> "move back to original position." 

I feel that this line should be in the case that no legal path is found, or else this algorithm will fail the function. You put it in such a way that makes me conclude that one would have to do this step even if a legal path is found.

**Comment by DevMMing** [comment]
Thank you for the constructive feedback. We are deeply grateful for allowing us to recognize the kinks in our documentation. No need to apologize; the help you provided was much needed to allow us to progress in this assignment.

For the recursive abstraction, my group has talked it over and felt that the recursive abstraction did not need any necessary changes. We acknowledged that the part of the description that might've been overlooked was the fact that the paths needed to be **legal**.

For the pseudocode, we botched the base case and readily fixed it at a moment's notice. We had also conversed about this issue and felt that it was necessary to leave it too as moving back to the original position allowed backtracking to occur when the path was not legal. We found that it might have been unclear that invoking the recursive abstraction would return a value, thereby ignoring the backtracking move if a legal path is found.

Although these issues weren't resolved, it helped us recognize how ambiguous our writing was and improve as programmers such that next time a similar issue comes up, we can quickly address it.
